appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: B5DE2mmCiFbVMJZ2wofJjVa+JLuMCRC99Fhvp1H8WvAqcsjVAx7pRSk/O+kV3zzZnXKxBcjv5pFhjx/yQ1oo/HDe5PNVfl7BbA3zAX8blLqHRPTpQdWOvz9SqGAT/bnNUpkUknSmx+n4WAEvoYjjH5rvU9sOEYRVgWH0DQ5/8Mb2rc7aP3gR3MkZrbMJc0RzObFZiydCOg0LvSa0VnQ9XK5w3eIyypnUPkzLNSpd9ifoKdOFXngGWGTcc7eM4Yu0Ekttxubtbxaa8jjSV6GQGGpHWiRsEZOuPbAGWYZ+t6j0tyRpngAhogXZwfe4bxzploA7T2lpkWgSWMH4tc05pGVcpHr+adKmv4Rm9/3SzGXWH3JHzkhROjZnENqYuwdyPbLwSMB7MXTILRBzsHzXlCGjVbOBu0Wx2yRFEyaYjqEMuoB7lMtP7oKPO6xrRy3U6ngCTdzWpIjSItlwQwewD2o5YOZYnW+bVTwt1owSX9V816J5OXHYNLvTYUZlsY3s84Mz7w8zA2N/y9JDGp6jHCYaclEpL78ybPAud8+AwvqNTELTwcBkc/CeHVcNDyV5FpvFvN1V6rjbPqdaSHIsZKrf9SRKw0tJaLqwjP/oKHWwpJ/eQt2X7JgZIu9mGQdIZUClyxSIALVbz5g1WYOu6CC4IK5Rgg6BiCxkrLt5DZA=
conda_forge_output_validation: true
